name: A workflow for my Hello World file
on: [push]
  
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::913427614577:role/GitHubActions
          aws-region: us-east-1
      - uses: ./action-a
        with:
          MY_NAME: "Duran"
      - name: Scan Docker image
        run: aws ecr start-image-scan --repository-name hello-github-actions --image-id imageDigest=sha256:7b11bec0796b89c493eb7d7d7ceaf1b2ec832bf070362002ed1a38511919ca57 --region us-east-1            
      - name: Logs for work summary
        run: |
           echo "### SRE logs for workflows! :rocket:" >> $GITHUB_STEP_SUMMARY
