name: A workflow for my Hello World file
on: push
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for custom workflow'
        required: true
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Duran"


