name: A workflow for my Hello World file
on: [push]
  
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Duran"

  
echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
