name: A workflow for my Hello World file
on: [push]
  
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: ./action-a
        with:
          MY_NAME: "Duran"
      - name: Build Docker image
        run: docker build -t your-image-name:latest .

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region your-region | docker login --username AWS --password-stdin your-account-id.dkr.ecr.your-region.amazonaws.com

      - name: Tag Docker image
        run: docker tag your-image-name:latest your-account-id.dkr.ecr.your-region.amazonaws.com/your-repository-name:latest

      - name: Push Docker image to AWS ECR
        run: docker push your-account-id.dkr.ecr.your-region.amazonaws.com/your-repository-name:latest  
      - name: Scan Docker image
        run: aws ecr start-image-scan --repository-name hello-github-actions --image-id imageDigest=sha256:7b11bec0796b89c493eb7d7d7ceaf1b2ec832bf070362002ed1a38511919ca57 --region us-east-1            
      - name: Logs for work summary
        run: |
           echo "### SRE logs for workflows! :rocket:" >> $GITHUB_STEP_SUMMARY
